import { Category, Product, Order } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat_all',
    name: 'All Bundles',
    slug: 'all',
    description: 'Explore the complete stock video vault',
    iconName: 'Sparkles',
    count: 18,
  },
  {
    id: 'cat_cars',
    name: 'Cars & Supercars',
    slug: 'cars',
    description: '4K HD luxury exhausts, hypercar acceleration, and night drives',
    iconName: 'Car',
    count: 2,
  },
  {
    id: 'cat_gym',
    name: 'Gym & Fitness',
    slug: 'gym',
    description: 'High-intensity workout reels, bodybuilding, and aesthetics',
    iconName: 'Dumbbell',
    count: 3,
  },
  {
    id: 'cat_motivation',
    name: 'Motivation & Mindset',
    slug: 'motivation',
    description: 'Cinematic speeches, discipline clips, and hard-hitting reels',
    iconName: 'Zap',
    count: 2,
  },
  {
    id: 'cat_luxury',
    name: 'Luxury & Lifestyle',
    slug: 'luxury',
    description: 'Yachts, penthouses, private jets, and wealth aesthetic clips',
    iconName: 'Crown',
    count: 2,
  },
  {
    id: 'cat_ai',
    name: 'AI & Futuristic',
    slug: 'ai',
    description: 'Next-gen cyberpunk visuals, AI avatars, and tech animation reels',
    iconName: 'Cpu',
    count: 3,
  },
  {
    id: 'cat_kids',
    name: 'Kids & Learning',
    slug: 'kids',
    description: '3D animated educational reels, stories, and kid-safe fun',
    iconName: 'Smile',
    count: 2,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_cars_blue',
    productId: 'CAR001_BLUE',
    title: '100+ Premium Cinematic Cars Reels Videos Bundle (Blue Edition)',
    slug: '100-premium-cinematic-cars-reels-videos-bundle-blue',
    category: 'cars',
    price: 349,
    originalPrice: 1299,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR001',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-blue.png',
    previewVideoUrl: '',
    clipCount: 100,
    fileSize: '5.1 GB',
    resolution: '4K Ultra HD',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['cars', 'supercars', 'luxury', '4k', 'speed', 'no copyright'],
    downloads: 620,
    rating: 5.0,
    active: true,
    featured: true,
    createdAt: '2026-08-01T11:00:00.000Z',
  },
  {
    id: 'prod_cars_red',
    productId: 'CAR001_RED',
    title: '100+ Premium Cinematic Cars Reels Videos Bundle (Red Edition)',
    slug: '100-premium-cinematic-cars-reels-videos-bundle-red',
    category: 'cars',
    price: 349,
    originalPrice: 1299,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR002',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-red.png',
    previewVideoUrl: '',
    clipCount: 100,
    fileSize: '5.4 GB',
    resolution: '4K Ultra HD',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['cars', 'supercars', 'jdm', '4k', 'night drives', 'no copyright'],
    downloads: 840,
    rating: 5.0,
    active: true,
    featured: true,
    createdAt: '2026-08-01T11:30:00.000Z',
  },
  {
    id: 'prod_mot_001',
    productId: 'MOT001',
    title: '1200+ Viral Motivational Speech Reels',
    slug: '1200-viral-motivational-speech-reels',
    category: 'motivation',
    price: 299,
    originalPrice: 899,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_MOT001',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=800&q=80',
    previewVideoUrl: '',
    clipCount: 1200,
    fileSize: '3.8 GB',
    resolution: '1080x1920',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['motivation', 'mindset', 'discipline', 'quotes'],
    downloads: 810,
    rating: 4.8,
    active: true,
    featured: true,
    createdAt: '2026-08-01T12:00:00.000Z',
  },
  {
    id: 'prod_lux_001',
    productId: 'LUX001',
    title: '600+ Billionaire Luxury Yacht & Penthouse Footage',
    slug: '600-billionaire-luxury-lifestyle-reels',
    category: 'luxury',
    price: 399,
    originalPrice: 1499,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_LUX001',
    thumbnailUrl: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=800&q=80',
    previewVideoUrl: '',
    clipCount: 600,
    fileSize: '4.5 GB',
    resolution: '4K Ultra HD',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['luxury', 'yacht', 'penthouse', 'lifestyle', 'wealth'],
    downloads: 315,
    rating: 4.9,
    active: true,
    featured: false,
    createdAt: '2026-08-01T13:00:00.000Z',
  },
  {
    id: 'prod_ai_001',
    productId: 'AI001',
    title: '500+ Cyberpunk & AI 3D Motion Reels',
    slug: '500-cyberpunk-ai-3d-motion-reels',
    category: 'ai',
    price: 249,
    originalPrice: 799,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_AI001',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    previewVideoUrl: '',
    clipCount: 500,
    fileSize: '2.9 GB',
    resolution: '1080x1920',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['ai', 'cyberpunk', '3d', 'future', 'technology'],
    downloads: 410,
    rating: 4.7,
    active: true,
    featured: true,
    createdAt: '2026-08-01T14:00:00.000Z',
  },
  {
    id: 'prod_kids_001',
    productId: 'KID001',
    title: '750+ 3D Animated Kids Rhymes & Story Reels',
    slug: '750-3d-animated-kids-rhymes-story-reels',
    category: 'kids',
    price: 299,
    originalPrice: 999,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_KID001',
    thumbnailUrl: 'https://images.unsplash.com/photo-1535572290543-960a8046f5af?auto=format&fit=crop&w=800&q=80',
    previewVideoUrl: '',
    clipCount: 750,
    fileSize: '3.9 GB',
    resolution: '1080x1920',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['kids', 'animation', 'stories', 'rhymes', 'learning'],
    downloads: 530,
    rating: 4.9,
    active: true,
    featured: false,
    createdAt: '2026-08-01T15:00:00.000Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_mock_101',
    orderId: 'ord_pay_101928374',
    userId: 'user_demo_123',
    productId: 'CAR001_BLUE',
    productTitle: '100+ Premium Cinematic Cars Reels Videos Bundle (Blue Edition)',
    productCategory: 'cars',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-blue.png',
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR001',
    razorpayOrderId: 'order_PxY101928374',
    razorpayPaymentId: 'pay_PxY101928374',
    amount: 349,
    currency: 'INR',
    status: 'SUCCESS',
    downloadCount: 2,
    lastDownloadedAt: '2026-08-02T12:00:00.000Z',
    createdAt: '2026-08-01T16:00:00.000Z',
  },
  {
    id: 'ord_mock_102',
    orderId: 'ord_pay_101928375',
    userId: 'user_demo_123',
    productId: 'CAR001_RED',
    productTitle: '100+ Premium Cinematic Cars Reels Videos Bundle (Red Edition)',
    productCategory: 'cars',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-red.png',
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR002',
    razorpayOrderId: 'order_PxY101928375',
    razorpayPaymentId: 'pay_PxY101928375',
    amount: 349,
    currency: 'INR',
    status: 'SUCCESS',
    downloadCount: 1,
    lastDownloadedAt: '2026-08-02T11:00:00.000Z',
    createdAt: '2026-08-01T17:00:00.000Z',
  },
];
