import { Category, Product, Order } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat_all',
    name: 'All Bundles',
    slug: 'all',
    description: 'Explore the complete stock video vault',
    iconName: 'Sparkles',
    count: 2,
  },
  {
    id: 'cat_cars',
    name: 'Cars & Supercars',
    slug: 'cars',
    description: '4K HD luxury exhausts, hypercar acceleration, and night drives',
    iconName: 'Car',
    count: 2,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_cars_blue',
    productId: 'CAR001_BLUE',
    title: '100+ Premium Cinematic Cars Reels Videos Bundle (Blue Edition)',
    slug: '100-premium-cinematic-cars-reels-videos-bundle-blue',
    category: 'cars',
    price: 349,
    originalPrice: 1299,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR001',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-blue.png',
    previewVideoUrl: '',
    clipCount: 100,
    fileSize: '5.1 GB',
    resolution: '4K Ultra HD',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['cars', 'supercars', 'luxury', '4k', 'speed', 'no copyright'],
    downloads: 620,
    rating: 5.0,
    active: true,
    featured: true,
    createdAt: '2026-08-01T11:00:00.000Z',
  },
  {
    id: 'prod_cars_red',
    productId: 'CAR001_RED',
    title: '100+ Premium Cinematic Cars Reels Videos Bundle (Red Edition)',
    slug: '100-premium-cinematic-cars-reels-videos-bundle-red',
    category: 'cars',
    price: 349,
    originalPrice: 1299,
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR002',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-red.png',
    previewVideoUrl: '',
    clipCount: 100,
    fileSize: '5.4 GB',
    resolution: '4K Ultra HD',
    aspectRatio: '9:16',
    format: 'MP4',
    tags: ['cars', 'supercars', 'jdm', '4k', 'night drives', 'no copyright'],
    downloads: 840,
    rating: 5.0,
    active: true,
    featured: true,
    createdAt: '2026-08-01T11:30:00.000Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_mock_101',
    orderId: 'ord_pay_101928374',
    userId: 'user_demo_123',
    productId: 'CAR001_BLUE',
    productTitle: '100+ Premium Cinematic Cars Reels Videos Bundle (Blue Edition)',
    productCategory: 'cars',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-blue.png',
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR001',
    razorpayOrderId: 'order_PxY101928374',
    razorpayPaymentId: 'pay_PxY101928374',
    amount: 349,
    currency: 'INR',
    status: 'SUCCESS',
    downloadCount: 2,
    lastDownloadedAt: '2026-08-02T12:00:00.000Z',
    createdAt: '2026-08-01T16:00:00.000Z',
  },
  {
    id: 'ord_mock_102',
    orderId: 'ord_pay_101928375',
    userId: 'user_demo_123',
    productId: 'CAR001_RED',
    productTitle: '100+ Premium Cinematic Cars Reels Videos Bundle (Red Edition)',
    productCategory: 'cars',
    thumbnailUrl: 'https://raw.githubusercontent.com/SalmanShaik101/stockvault/main/public/cars-bundle-red.png',
    driveFileId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_CAR002',
    razorpayOrderId: 'order_PxY101928375',
    razorpayPaymentId: 'pay_PxY101928375',
    amount: 349,
    currency: 'INR',
    status: 'SUCCESS',
    downloadCount: 1,
    lastDownloadedAt: '2026-08-02T11:00:00.000Z',
    createdAt: '2026-08-01T17:00:00.000Z',
  },
];
